spring:
  datasource:
    url: jdbc:mysql://localhost/assigmnentjava?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 10MB
  config:
    activate:
      on-profile: prod
server:
  port: 8080
environment: production
name: prod-YAML
enabled: true
servers:
  - localhost:8080
file:
  upload-dir:dokumen